In [13]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [14]:
df_GATC = pd.read_csv(r'train.csv')

In [15]:
df_GATC.head()

row_id     A0T0G0C10  A0T0G1C9  A0T0G2C8  A0T0G3C7  A0T0G4C6  A0T0G5C5  \
0       0 -9.536743e-07 -0.000010 -0.000043 -0.000114 -0.000200 -0.000240   
1       1 -9.536743e-07 -0.000010 -0.000043  0.000886 -0.000200  0.000760   
2       2 -9.536743e-07 -0.000002  0.000007  0.000129  0.000268  0.000270   
3       3  4.632568e-08 -0.000006  0.000012  0.000245  0.000492  0.000522   
4       4 -9.536743e-07 -0.000010 -0.000043 -0.000114 -0.000200 -0.000240   

   A0T0G6C4  A0T0G7C3  A0T0G8C2  ...  A8T0G1C1  A8T0G2C0  A8T1G0C1  A8T1G1C0  \
0 -0.000200 -0.000114 -0.000043  ... -0.000086 -0.000043 -0.000086 -0.000086   
1 -0.000200 -0.000114 -0.000043  ... -0.000086 -0.000043  0.000914  0.000914   
2  0.000243  0.000125  0.000001  ...  0.000084  0.000048  0.000081  0.000106   
3  0.000396  0.000197 -0.000003  ...  0.000151  0.000100  0.000180  0.000202   
4 -0.000200 -0.000114 -0.000043  ... -0.000086 -0.000043 -0.000086 -0.000086   

   A8T2G0C0  A9T0G0C1  A9T0G1C0  A9T1G0C0     A10T0G0C0  \
0 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07   
1 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07   
2  0.000072  0.000010  0.000008  0.000019  1.046326e-06   
3  0.000153  0.000021  0.000015  0.000046 -9.536743e-07   
4 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07   

                   target  
0  Streptococcus_pyogenes  
1     Salmonella_enterica  
2     Salmonella_enterica  
3     Salmonella_enterica  
4      Enterococcus_hirae  

[5 rows x 288 columns]

In [16]:
df_GATC.shape

(200000, 288)

In [17]:
df_GATC.columns.values

array(['row_id', 'A0T0G0C10', 'A0T0G1C9', 'A0T0G2C8', 'A0T0G3C7',
       'A0T0G4C6', 'A0T0G5C5', 'A0T0G6C4', 'A0T0G7C3', 'A0T0G8C2',
       'A0T0G9C1', 'A0T0G10C0', 'A0T1G0C9', 'A0T1G1C8', 'A0T1G2C7',
       'A0T1G3C6', 'A0T1G4C5', 'A0T1G5C4', 'A0T1G6C3', 'A0T1G7C2',
       'A0T1G8C1', 'A0T1G9C0', 'A0T2G0C8', 'A0T2G1C7', 'A0T2G2C6',
       'A0T2G3C5', 'A0T2G4C4', 'A0T2G5C3', 'A0T2G6C2', 'A0T2G7C1',
       'A0T2G8C0', 'A0T3G0C7', 'A0T3G1C6', 'A0T3G2C5', 'A0T3G3C4',
       'A0T3G4C3', 'A0T3G5C2', 'A0T3G6C1', 'A0T3G7C0', 'A0T4G0C6',
       'A0T4G1C5', 'A0T4G2C4', 'A0T4G3C3', 'A0T4G4C2', 'A0T4G5C1',
       'A0T4G6C0', 'A0T5G0C5', 'A0T5G1C4', 'A0T5G2C3', 'A0T5G3C2',
       'A0T5G4C1', 'A0T5G5C0', 'A0T6G0C4', 'A0T6G1C3', 'A0T6G2C2',
       'A0T6G3C1', 'A0T6G4C0', 'A0T7G0C3', 'A0T7G1C2', 'A0T7G2C1',
       'A0T7G3C0', 'A0T8G0C2', 'A0T8G1C1', 'A0T8G2C0', 'A0T9G0C1',
       'A0T9G1C0', 'A0T10G0C0', 'A1T0G0C9', 'A1T0G1C8', 'A1T0G2C7',
       'A1T0G3C6', 'A1T0G4C5', 'A1T0G5C4', 'A1T0G6C3', 'A1T0G

In [18]:
df_GATC.isnull().values.any()

False

In [19]:
df_GATC.dtypes

row_id         int64
A0T0G0C10    float64
A0T0G1C9     float64
A0T0G2C8     float64
A0T0G3C7     float64
              ...   
A9T0G0C1     float64
A9T0G1C0     float64
A9T1G0C0     float64
A10T0G0C0    float64
target        object
Length: 288, dtype: object

In [20]:
# Import necessary modules
X = df_GATC.drop(columns =['target', 'row_id']).values
y = df_GATC['target'].values

# Create training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

# Instantiate a k-NN classifier: knn
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Predict the labels of the test data: y_pred
y_pred = knn.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[7638   19   46   56   44   11   26   46   92   66]
 [  24 7791   54    9    1    6    7  175   18   22]
 [  56   45 7508   10   10    9   11   74   89  121]
 [  50    8   21 7500  143   51   79    6   21   15]
 [  70    4   22  225 7539   61   74   14   12   10]
 [  22    2    9   91   78 7627   82    1    8    1]
 [  47    9   27  175  134   97 7558    8    9   10]
 [  27  199  100   22    6    2   11 7517   43   34]
 [  95   45  179   28   28    8   20   47 7491   91]
 [  75   45  226   20   36    1   16   94  121 7369]]
                          precision    recall  f1-score   support

    Bacteroides_fragilis       0.94      0.95      0.95      8044
    Campylobacter_jejuni       0.95      0.96      0.96      8107
      Enterococcus_hirae       0.92      0.95      0.93      7933
        Escherichia_coli       0.92      0.95      0.94      7894
  Escherichia_fergusonii       0.94      0.94      0.94      8031
   Klebsiella_pneumoniae       0.97      0.96      0.97      7921
     S

In [21]:
mat=confusion_matrix(y_test, y_pred)
numpy.savetxt("prediction.csv", mat, delimiter=",")